/**
 * Offline connectivity analysis for the road-mask experiment.
 *
 * Reconstructs the brief's metric from a captured raster dump: the open
 * (non-building, tile-covered) cells form a graph; what the player experiences
 * is whether that graph is connected. Reports, per variant:
 *   - covered cells, building cells, open cells
 *   - connected open regions (4-connectivity) and the largest as % of covered
 *
 * The capture file round-trips typed arrays through JSON, which turns the ±Inf
 * no-data sentinels into null and the arrays into key-value objects — both get
 * revived here, in the generated test, before the real pipeline sees them.
 *
 * Usage: node scripts/analyze-roads.mjs <capture.json> <city-name>
 * Generates tests/tmp-measure-<city>.test.ts; run it with vitest, then delete.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const capturePath = process.argv[2];
const cityName = process.argv[3] ?? 'unknown';
if (!capturePath) {
  console.error('usage: node scripts/analyze-roads.mjs <capture.json> <city>');
  process.exit(1);
}

const capture = JSON.parse(readFileSync(capturePath, 'utf8'));
const { grid, origin } = capture;

// reliefBoost: the live value when the capture recorded it, else derived from
// the terrainTop range. terrainTop ≈ DEMrange × boost (+GROUND_LIFT), and
// reliefBoostFor(range) has only narrow ambiguous bands, so the inversion is
// unique in practice (SF: 230.5 m → 1.2).
function deriveReliefBoost(terrainTop) {
  let mn = Infinity, mx = -Infinity;
  for (const k in terrainTop) {
    const v = terrainTop[k];
    if (v < mn) mn = v;
    if (v > mx) mx = v;
  }
  const r = mx - mn;
  for (const [lo, hi, b] of [[0, 104, 1.3], [96, 360, 1.2], [330, 1100, 1.1], [1000, Infinity, 1.0]]) {
    if (r >= lo && r < hi) return b;
  }
  return 1;
}
const reliefBoost = capture.reliefBoost ?? deriveReliefBoost(capture.terrainTop);

const testFile = `// AUTO-GENERATED by scripts/analyze-roads.mjs — TEMP, delete after measuring
import { readFileSync } from 'node:fs';
import { describe, it } from 'vitest';
import { collidersFromRasters, type TileRaster } from '../src/services/tiles/tileColliders.ts';
import { fetchRoadPolylines, rasterizeRoads } from '../src/services/osm/roads.ts';

const capture = JSON.parse(readFileSync(${JSON.stringify(capturePath)}, 'utf8'));
const grid = capture.grid;
const RELIEF = ${reliefBoost};

// JSON turned typed arrays into key-value objects and ±Inf sentinels into null
const revive = (o: Record<string, number | null>, nullTo: number): Float32Array =>
  Float32Array.from(Object.values(o), v => (v === null ? nullTo : (v as number)));
const terrainTop = revive(capture.terrainTop, -Infinity);
const rasters: (TileRaster | null)[] = capture.rasters.map((r: any) =>
  r ? {
    i0: r.i0, j0: r.j0, w: r.w, h: r.h, y0: r.y0,
    top: revive(r.top, -Infinity),
    low: revive(r.low, Infinity),
    mask: Uint32Array.from(Object.values(r.mask))
  } : null);

function measure(roadMask: any) {
  const n = grid.n;
  const structureGrid = new Uint8Array(n * n);
  const t0 = performance.now();
  const boxes = collidersFromRasters(rasters, grid, terrainTop, RELIEF, undefined, undefined, structureGrid, roadMask);
  const ms = (performance.now() - t0).toFixed(0);
  // covered = a raster with actual geometry (top !== -Inf) at the cell
  const covered = new Uint8Array(n * n);
  let coveredCount = 0;
  for (const r of rasters) {
    if (!r) continue;
    for (let j = 0; j < r.h; j++) {
      for (let i = 0; i < r.w; i++) {
        if (r.top[j * r.w + i] === -Infinity) continue;
        const c = (r.j0 + j) * n + r.i0 + i;
        if (!covered[c]) { covered[c] = 1; coveredCount++; }
      }
    }
  }
  const open = new Uint8Array(n * n);
  let openCount = 0;
  for (let c = 0; c < n * n; c++) {
    if (covered[c] && !structureGrid[c]) { open[c] = 1; openCount++; }
  }
  const label = new Int32Array(n * n).fill(-1);
  const regions: number[] = [];
  for (let c0 = 0; c0 < n * n; c0++) {
    if (!open[c0] || label[c0] >= 0) continue;
    const id = regions.length;
    let size = 0;
    const stack = [c0];
    label[c0] = id;
    while (stack.length) {
      const c = stack.pop()!;
      size++;
      const i = c % n, j = (c - i) / n;
      const push = (nc: number) => { if (nc >= 0 && open[nc] && label[nc] < 0) { label[nc] = id; stack.push(nc); } };
      if (i > 0) push(c - 1);
      if (i < n - 1) push(c + 1);
      if (j > 0) push(c - n);
      if (j < n - 1) push(c + n);
    }
    regions.push(size);
  }
  regions.sort((a, b) => b - a);
  return {
    ms, boxes: boxes.length, covered: coveredCount,
    buildingPct: (100 * (coveredCount - openCount) / coveredCount).toFixed(1),
    openPct: (100 * openCount / coveredCount).toFixed(1),
    regions: regions.length,
    largestPct: (100 * (regions[0] ?? 0) / coveredCount).toFixed(1),
    top5: regions.slice(0, 5)
  };
}

describe('connectivity: ${cityName}', () => {
  it('baseline vs +roads', async () => {
    const base = measure(null);
    console.log('${cityName} baseline:', JSON.stringify(base));
    const polys = await fetchRoadPolylines({ lat: ${JSON.stringify(origin?.lat)}, lon: ${JSON.stringify(origin?.lon)}, halfM: grid.half });
    if (!polys) { console.log('${cityName} roads: FETCH FAILED'); return; }
    console.log('${cityName} polylines:', polys.length);
    const roads = rasterizeRoads(polys, grid);
    let masked = 0;
    for (const v of roads.mask) if (v) masked++;
    console.log('${cityName} road cells:', masked);
    const withRoads = measure(roads);
    console.log('${cityName} +roads:', JSON.stringify(withRoads));
  });
});
`;
const outFile = `tests/tmp-measure-${cityName}.test.ts`;
writeFileSync(outFile, testFile);
console.log(`city ${cityName}: grid ${grid.n}x${grid.n} cell ${grid.cell}, reliefBoost ${reliefBoost}`);
console.log(`generated ${outFile}`);
console.log(`run: npx vitest run ${outFile}`);
